name: Devanddeploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: docker.io/ravkr77751/dockertest
      credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          steps:
            name: Checkout
            uses: actions/checkout@v3
            name: rundevscript
            run: ./dev_run.sh
      

